apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: env0-state-volume-claim
  namespace: env0-agent
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
  storageClassName: local-path
  volumeMode: Filesystem